# Setup
title: Concluding Postscript
# email: girishji_[delete_underscore][at]gmail[dot]com
# email: girishji@gmail.com
emailme: mailto:girishji@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Code, family, and Kierkegaard.
baseurl: "" 
url: "" 
twitter_username: 
github_username:  girishji

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
# theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

