# Setup
title: Concluding Postscript
# email: girishji_[delete_underscore][at]gmail[dot]com
# email: girishji@gmail.com
emailme: mailto:girishji@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Code, family, and Kierkegaard.
baseurl: "" 
url: "" 
twitter_username: 
github_username:  girishji

# Build settings
markdown: kramdown

remote_theme: "mmistakes/so-simple-theme@3.2.0"
# remote_theme: pages-themes/minimal@v0.2.0
# theme: jekyll-theme-slate
# theme: jekyll-theme-hacker

plugins:
  - jekyll-feed
  - jekyll-remote-theme
