# Setup
title: Optical Matrix
# email: girishji_[delete_underscore][at]gmail[dot]com
# email: girishji@gmail.com
emailme: mailto:girishji@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Low Latency Optical Keyboards
baseurl: "" 
url: "" 
twitter_username: 
github_username:  girishji
author: Girish

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

remote_theme: "mmistakes/so-simple-theme@3.2.0"
# remote_theme: "broccolini/athena"
# remote_theme: "yous/whiteglass"
# theme: jekyll-theme-slate
# theme: jekyll-theme-hacker


plugins:
  - jekyll-remote-theme
  # - jekyll-feed
  # - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  
# Needed by whiteglass theme
exclude:
  bak/

google_analytics: G-ZYNKCMZ206

permalink: /:year/:month/:day/:title/
# permalink: /:categories/:year/:month/:day/:title:output_ext
# permalink: /:categories/:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
