# Setup
title: Optical Matrix
# email: girishji_[delete_underscore][at]gmail[dot]com
# email: girishji@gmail.com
emailme: mailto:girishji@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Low Latency Optical Keyboards
baseurl: "" 
url: "" 
twitter_username: 
github_username:  girishji
author: Girish

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: G-ZYNKCMZ206
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"
feed:
  path: atom.xml
# permalink: /:categories/:title/
permalink: /:year/:month/:day/:title/
# permalink: /:categories/:year/:month/:day/:title:output_ext
# permalink: /:categories/:year/:month/:day/:title/

remote_theme: "mmistakes/so-simple-theme@3.2.0"
# remote_theme: "broccolini/athena"
# remote_theme: "yous/whiteglass"
# theme: jekyll-theme-slate
# theme: jekyll-theme-hacker


plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  # - jekyll-archives
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - bak/
  - Gemfile



# Pagination
paginate_path: /posts/:num/
paginate: 5

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
