# Setup
title: girish
# email: girishji_[delete_underscore][at]gmail[dot]com
# email: girishji@gmail.com
emailme: mailto:girishji@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Building Things
baseurl: ""
url: ""
twitter_username:
github_username:  girishji
author: Girish

# google_fonts:
#   - name: "Source Sans Pro"
#     weights: "400,400i,700,700i"
#   - name: "Lora"
#     weights: "400,400i,700,700i"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"
feed:
  path: atom.xml
# permalink: /:categories/:title/
permalink: /:year/:month/:day/:title/
# permalink: /:categories/:year/:month/:day/:title:output_ext
# permalink: /:categories/:year/:month/:day/:title/

# remote_theme: "mmistakes/so-simple-theme@3.2.0"
# remote_theme: "tocttou/hacker-blog"
# remote_theme: "yous/whiteglass"
# theme: jekyll-theme-slate
# theme: jekyll-theme-hacker
theme: jekyll-theme-minima

# Use Gem-based method instead of remote_theme
# With Gem-based themes, directories such as the assets, _layouts, _includes, and
# _sass are stored in the theme’s gem, hidden from your immediate view. Yet all
# of the necessary directories will be read and processed during Jekyll’s build
# process.
# See https://github.com/b2a3e8/jekyll-theme-console

# theme: jekyll-theme-console

# Theme jekyll-theme-console specific configuration
# header_pages:
#   - index.md
#   - about.md
#
# style: dark # dark (default), light or hacker
# listen_for_clients_preferred_style: true # false (default) or true
#
# footer: '<a href="https://github.com/girishji">github page</a>'
#
# google_analytics: G-ZYNKCMZ206
#
# end of jekyll-theme-console

google_analytics: G-ZYNKCMZ206

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  # - jekyll-archives
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - bak/
  - Gemfile
  - help.txt



# Pagination
paginate_path: /posts/:num/
paginate: 5

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
