# Setup
title: Optical Matrix
# email: girishji_[delete_underscore][at]gmail[dot]com
# email: girishji@gmail.com
emailme: mailto:girishji@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Low Latency Optical Keyboards.
baseurl: "" 
url: "" 
twitter_username: 
github_username:  girishji
author: Girish

# Build settings
markdown: kramdown

# remote_theme: "mmistakes/so-simple-theme@3.2.0"
# remote_theme: "broccolini/athena"
# remote_theme: "yous/whiteglass"
# theme: jekyll-theme-slate
# theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0


plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  
# Needed by the theme

google_analytics: G-ZYNKCMZ206

permalink: /:year/:month/:day/:title/
# permalink: /:categories/:year/:month/:day/:title:output_ext
# permalink: /:categories/:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
